import fs from "node:fs/promises";
import path from "node:path";
import type {
    AndroidForegroundDecisionKind,
    AndroidForegroundFixtureDocument,
    AndroidForegroundState,
} from "../src-backend/services/AndroidForegroundProtocol";

interface CliArgs {
    outputPath: string;
    id: string;
    label: string;
    description: string;
    state: AndroidForegroundState;
    screenshotPaths: string[];
}

function parseArgs(argv: string[]): CliArgs {
    const args: CliArgs = {
        outputPath: "",
        id: "",
        label: "",
        description: "",
        state: "UNKNOWN",
        screenshotPaths: [],
    };

    for (let index = 0; index < argv.length; index += 1) {
        const token = argv[index];
        if (token === "--output" && argv[index + 1]) {
            args.outputPath = path.resolve(argv[index + 1]);
            index += 1;
            continue;
        }

        if (token === "--id" && argv[index + 1]) {
            args.id = argv[index + 1];
            index += 1;
            continue;
        }

        if (token === "--label" && argv[index + 1]) {
            args.label = argv[index + 1];
            index += 1;
            continue;
        }

        if (token === "--description" && argv[index + 1]) {
            args.description = argv[index + 1];
            index += 1;
            continue;
        }

        if (token === "--state" && argv[index + 1]) {
            args.state = argv[index + 1] as AndroidForegroundState;
            index += 1;
            continue;
        }

        if (token === "--screenshot" && argv[index + 1]) {
            args.screenshotPaths.push(path.resolve(argv[index + 1]));
            index += 1;
        }
    }

    if (!args.outputPath || !args.id || !args.label || !args.description || args.screenshotPaths.length === 0) {
        throw new Error("缺少必要参数: --output --id --label --description --state --screenshot");
    }

    return args;
}

function inferExpectedDecisionKind(state: AndroidForegroundState, frameIndex: number): AndroidForegroundDecisionKind {
    switch (state) {
        case "UPDATE_READY":
            return frameIndex === 0 ? "WAIT" : frameIndex === 1 ? "TAP_PRIMARY_CTA" : "WAIT";
        case "LOGIN_REQUIRED":
            return "BLOCKED";
        case "LOBBY":
            return frameIndex === 0 ? "WAIT" : frameIndex === 1 ? "TAP_START_QUEUE" : "WAIT";
        case "QUEUE":
            return "WAIT";
        case "ACCEPT_READY":
            return frameIndex === 0 ? "TAP_ACCEPT_READY" : "WAIT";
        case "IN_GAME_TRANSITION":
            return "WAIT";
        case "LIVE_CONTENT":
            return "READY";
        case "BLUESTACKS_BOOT":
        case "UNKNOWN":
        default:
            return "WAIT";
    }
}

async function main(): Promise<void> {
    const args = parseArgs(process.argv.slice(2));
    const outputDir = path.dirname(args.outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    const document: AndroidForegroundFixtureDocument = {
        schemaVersion: "android-foreground-fixture.v1",
        id: args.id,
        label: args.label,
        description: args.description,
        notes: [
            "Generated by scripts/scaffold-android-foreground-fixture.ts.",
            "Review expectedDecisionKind and anchor notes before treating the fixture as verified.",
        ],
        frames: args.screenshotPaths.map((screenshotPath, index) => ({
            id: `${args.state.toLowerCase()}-${index + 1}`,
            label: `${args.state} frame ${index + 1}`,
            screenshotPath: path.relative(outputDir, screenshotPath).replace(/\\/g, "/"),
            expectedDecisionKind: inferExpectedDecisionKind(args.state, index),
            note: `Scaffolded from screenshot ${index + 1}. Update anchors, notes, and verification status after review.`,
        })),
    };

    await fs.writeFile(args.outputPath, `${JSON.stringify(document, null, 2)}\n`, "utf8");
    process.stdout.write(`${JSON.stringify({ outputPath: args.outputPath, frameCount: document.frames.length }, null, 2)}\n`);
}

main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
    process.exitCode = 1;
});
